export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Features } from './Features'
export { default as Contact } from './Contact'
export { default as Login } from './Login'
export { default as Register } from './Register'
